### ISSUE TITLE
[Button] Dense button text is out of bounds when split

### ISSUE THREAD

**Issue by acelletti** [Vonage/vivid#1350] opened 2022-11-01 11:02 UTC
**Describe the bug**
The dense button in our layout has a fixed width depending on the page size and it is causing the button to show the text out of bounds (I believe the line height might be too high).

<img width="112" alt="Screenshot 2022-11-01 at 11 00 41" src="https://user-images.githubusercontent.com/37002976/199218785-f37c7ded-5ae8-4d9b-84f2-553a18e3017f.png">

**To Reproduce**
See below as I have reproduced it inside the vivid storybook by just changing the label to `Getting Started` and adding a `max-width=100px`.

**Expected behavior**
The text should render in the center of the button.

**Screenshots**
<img width="1848" alt="Screenshot 2022-11-01 at 10 57 48" src="https://user-images.githubusercontent.com/37002976/199218621-71be5b31-0002-44ef-8bbf-69cdab15f390.png">

**Comment by yinonov** [comment] 2022-11-01 15:05
Although this is certainly a fixable bug (and already addressed in [vivid@next](https://vivid.deno.dev/components/button)), what is the expectation if the text exceeds it's available inline size? Would a trimmed / ellipsis text be better?

**Comment by acelletti** [comment] 2022-11-03 07:55
I would think the simplest solution would be this:

<img width="1851" alt="Screenshot 2022-11-03 at 07 55 22" src="https://user-images.githubusercontent.com/37002976/199670783-801c9272-cfc5-44ce-822d-09bed3088595.png">

**Comment by yinonov** [comment] 2022-11-03 17:28
I, myself, don't agree a button should be flexible in its block size, but I'd leave that decision for designers...
buttons is defined by design to have a fixed block size.

maybe [stacked button](https://vivid.vonage.com/?path=/story/components-button--stacked&args=label:lorem+ipsum+dolor;layout:filled;icon:;stacked:) would be better for this use-case?

**Comment by acelletti** [comment] 2022-11-05 09:10
@yinonov can we at least fix this issue by setting a `line-height` that is more in line with the `font-size`. `line-height` is usually set to `font-size + 2px` and in this case, the `font-size` is `12px` and `line-height` is `24px`.

All I am asking is that we change this in the next version so as to be unblocked.

> maybe [stacked button](https://vivid.vonage.com/?path=/story/components-button--stacked&args=label:lorem+ipsum+dolor;layout:filled;icon:;stacked:) would be better for this use-case?

Not really, all I need is a dense button that can handle rendering on two lines if the text is too long for the width.

**Comment by yinonov** [comment] 2022-11-05 11:27
Sure reducing the line-height is a reasonable solution and enhancement. Will do 👍

**Comment by acelletti** [comment] 2022-11-08 09:44
@yinonov thanks for addressing the issue quickly. 

Please, let me know when the fix is released so I can update our dependency.

**Closed** 2022-11-08 14:43 UTC

**Comment by yinonov** [comment] 2022-11-08 14:44
will release momentarily. see - [Prepare Vivid for release](https://github.com/Vonage/vivid/actions/runs/3420428502)

**Comment by acelletti** [comment] 2022-11-11 09:20
Still an issue in [v2.36.2](https://github.com/Vonage/vivid/releases/tag/v2.36.2).

<img width="1906" alt="Screenshot 2022-11-11 at 09 18 36" src="https://user-images.githubusercontent.com/37002976/201308186-f199be3c-5e56-4a73-8f3c-d3afac704736.png">

**Comment by yinonov** [comment] 2022-11-11 16:36
fixed in [v2.36.3](https://github.com/Vonage/vivid/releases/tag/v2.36.3)
<img width="410" alt="image" src="https://user-images.githubusercontent.com/15140652/201387190-14d45b06-e238-48d3-aff1-90f987ca2aa6.png">
